# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\"_\n\x12\x43reateOrderRequest\x12\x13\n\x0b\x63ostumer_id\x18\x01 \x01(\x05\x12\x1f\n\x0border_items\x18\x02 \x03(\x0b\x32\n.OrderItem\x12\x13\n\x0btotal_price\x18\x03 \x01(\x02\"G\n\tOrderItem\x12\x14\n\x0cproduct_code\x18\x01 \x01(\t\x12\x12\n\nunit_price\x18\x02 \x01(\x02\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"\'\n\x13\x43reateOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x32>\n\x05Order\x12\x35\n\x06\x43reate\x12\x13.CreateOrderRequest\x1a\x14.CreateOrderResponse\"\x00\x42\x30Z.github/ruandg/microservices-proto/golang/orderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github/ruandg/microservices-proto/golang/order'
  _globals['_CREATEORDERREQUEST']._serialized_start=15
  _globals['_CREATEORDERREQUEST']._serialized_end=110
  _globals['_ORDERITEM']._serialized_start=112
  _globals['_ORDERITEM']._serialized_end=183
  _globals['_CREATEORDERRESPONSE']._serialized_start=185
  _globals['_CREATEORDERRESPONSE']._serialized_end=224
  _globals['_ORDER']._serialized_start=226
  _globals['_ORDER']._serialized_end=288
# @@protoc_insertion_point(module_scope)
